[2024-02-28T16:29:49.731+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-28T16:24:43.491411+00:00 [queued]>
[2024-02-28T16:29:49.744+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-28T16:24:43.491411+00:00 [queued]>
[2024-02-28T16:29:49.745+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 4
[2024-02-28T16:29:49.765+0000] {taskinstance.py:2191} INFO - Executing <Task(GCSObjectExistenceSensor): gcs_object_exists> on 2024-02-28 16:24:43.491411+00:00
[2024-02-28T16:29:49.772+0000] {standard_task_runner.py:60} INFO - Started process 64 to run task
[2024-02-28T16:29:49.777+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'gcs_object_exists', 'manual__2024-02-28T16:24:43.491411+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpfpyinfdu']
[2024-02-28T16:29:49.782+0000] {standard_task_runner.py:88} INFO - Job 252: Subtask gcs_object_exists
[2024-02-28T16:29:49.850+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.gcs_object_exists manual__2024-02-28T16:24:43.491411+00:00 [running]> on host 1753c686362f
[2024-02-28T16:29:49.949+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='gcs_object_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T16:24:43.491411+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T16:24:43.491411+00:00'
[2024-02-28T16:29:49.951+0000] {gcs.py:98} INFO - Sensor checks existence of : us_stock_market, row_data/US-Stock-Market-2020-to-2024-Row-Data.csv
[2024-02-28T16:29:49.963+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-28T16:29:49.969+0000] {base.py:83} INFO - Using connection ID 'gcp_conn_id' for task execution.
[2024-02-28T16:29:50.473+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-02-28T16:29:50.493+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=gcs_snowflake_etl, task_id=gcs_object_exists, execution_date=20240228T162443, start_date=20240228T162949, end_date=20240228T162950
[2024-02-28T16:29:50.554+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-28T16:29:50.623+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
